# Generated by Django 2.2.4 on 2020-03-17 01:11

from django.db import migrations, models
import django.db.models.deletion
import otree.currency
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('project_a_funded', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('project_b_funded', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('project_c_funded', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('project_a_total_amount', otree.db.models.CurrencyField(default=otree.currency.Currency('0'), null=True)),
                ('project_b_total_amount', otree.db.models.CurrencyField(default=otree.currency.Currency('0'), null=True)),
                ('project_c_total_amount', otree.db.models.CurrencyField(default=otree.currency.Currency('0'), null=True)),
                ('project_a_backer', otree.db.models.IntegerField(default=0, null=True)),
                ('project_b_backer', otree.db.models.IntegerField(default=0, null=True)),
                ('project_c_backer', otree.db.models.IntegerField(default=0, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bach_test_group', to='otree.Session')),
            ],
            options={
                'db_table': 'bach_test_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bach_test_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'bach_test_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('money_left', otree.db.models.CurrencyField(default=otree.currency.Currency('1000'), null=True)),
                ('project_a_contribution', otree.db.models.CurrencyField(default=otree.currency.Currency('0'), null=True, verbose_name='Wie viel möchtest du an Projekt A spenden?')),
                ('project_b_contribution', otree.db.models.CurrencyField(default=otree.currency.Currency('0'), null=True, verbose_name='Wie viel möchtest du an Projekt B spenden?')),
                ('project_c_contribution', otree.db.models.CurrencyField(default=otree.currency.Currency('0'), null=True, verbose_name='Wie viel möchtest du an Projekt C spenden?')),
                ('project_a_payoff', otree.db.models.CurrencyField(null=True)),
                ('project_b_payoff', otree.db.models.CurrencyField(null=True)),
                ('project_c_payoff', otree.db.models.CurrencyField(null=True)),
                ('a_is_backer', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('b_is_backer', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('c_is_backer', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('submit_a', otree.db.models.BooleanField(choices=[[True, 'Ja'], [False, 'Nein']], default=False, null=True, verbose_name='Übernehmen')),
                ('submit_b', otree.db.models.BooleanField(choices=[[True, 'Ja'], [False, 'Nein']], default=False, null=True, verbose_name='Übernehmen')),
                ('submit_c', otree.db.models.BooleanField(choices=[[True, 'Ja'], [False, 'Nein']], default=False, null=True, verbose_name='Übernehmen')),
                ('backout_a', otree.db.models.BooleanField(choices=[[True, 'Backout'], [False, 'Kein Backout']], default=False, null=True, verbose_name='Backout?')),
                ('backout_b', otree.db.models.BooleanField(choices=[[True, 'Backout'], [False, 'Kein Backout']], default=False, null=True, verbose_name='Backout?')),
                ('backout_c', otree.db.models.BooleanField(choices=[[True, 'Backout'], [False, 'Kein Backout']], default=False, null=True, verbose_name='Backout?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bach_test.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bach_test_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bach_test_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bach_test.Subsession')),
            ],
            options={
                'db_table': 'bach_test_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bach_test.Subsession'),
        ),
    ]
